# Generated by Django 5.1.2 on 2024-10-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bankoperation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankOperation',
        ),
    ]
