# Generated by Django 5.1.2 on 2024-10-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bankaccountoperation_delete_bankoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountoperation',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Deposit')], max_length=10),
        ),
    ]
