# Generated by Django 5.1.2 on 2024-10-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_bankoperation_operation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankoperation',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('transfer', 'Transfer')], default='withdraw', max_length=20),
            preserve_default=False,
        ),
    ]
