# Generated by Django 5.1.2 on 2024-10-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bankoperation_operation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankoperation',
            old_name='operation_type',
            new_name='operation_typed',
        ),
    ]
