# Generated by Django 5.1.2 on 2024-10-20 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_operation_type_bankoperation_operation_typed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankoperation',
            old_name='operation_typed',
            new_name='operation_type',
        ),
        migrations.AddField(
            model_name='bankoperation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
