# Generated by Django 5.1.2 on 2024-10-21 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='amount',
            new_name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='account',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='granted_at',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='paid_off',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='remaining_balance',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_duration_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
