# Generated by Django 5.1.2 on 2024-10-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_loans_delete_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='months',
            field=models.IntegerField(default=12),
        ),
    ]
